### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by NikolaM-Dev** [saifulapm/nvim#1]
How can I install your configuration?  and how do I install the lsps: c

**Comment by saifulapm** [comment]
Just git clone and open nvim

```
git clone https://github.com/saifulapm/nvim.git ~/.config/nvim
```

then open nvim

That's all

**Comment by saifulapm** [comment]
For LSPs:

```
npm i -g bash-language-server
npm i -g intelephense
```

For Lua Language Server
```
https://github.com/sumneko/lua-language-server/wiki/Build-and-Run-(Standalone)
```

Anyway, You can check my dotfiles where all config available. Use NVIM with Kitty for Best Performance
```
https://github.com/saifulapm/dotfiles
```
