### ISSUE TITLE
Certain glyphs not working with Nerd Font patched fonts

### ISSUE THREAD

**Issue by MatthewCushing** [saifulapm/nvim#3]
I was curious if you're using your own custom patched fonts?  If so, I was wondering if you might provide the glyphs or resources to patch myself or the fonts themselves to snag the glyphs from.  I have personally patched my own versions of Operator Mono with Nerd Fonts font-patcher script using `fontforge` (and used the Operator Mono ligaturizer repo patcher to add ligs to the font),  tried a couple other pre-patched Nerd Fonts, as well as tried using the Meslo NG Font that PowerLevel10K suggests using to get the most out of glyphs and such.  Even so, I get squares with question marks inside of them for the corners of your floating windows (among other borders) as well as question marks for the last 8 or so values in the `codicons`, and `nerdfonts` tables that are inside of the `kinds` table.  I've provided a couple images below to better visualize my meaning, thanks!

<details>
<summary>Border corners</summary>

<img width="522" alt="image" src="https://user-images.githubusercontent.com/10594068/181217904-7b03f800-08ca-4a4e-a981-950352217a51.png">

</details>

<details>
<summary>Codicons, and Nerdfonts table picture</summary>

<img width="247" alt="image" src="https://user-images.githubusercontent.com/10594068/181217279-95ed35c6-7d87-412a-8e97-080f881b6f06.png">

<img width="247" alt="image" src="https://user-images.githubusercontent.com/10594068/181217400-948bb928-450b-44e6-9093-7165e5bc8b4d.png">

</details>

I don't mind providing my own glyphs for these to replace them.  You've just done such a damn good job at making this editor look amazing that I need to know what it should look like and what I'm missing when I feel I've done all you can do to a font (for most developers) haha 

Thanks!

**EDIT**: If you put those question marks and question mark boxes in those places purposefully for a unique look, you can go ahead and have a laugh and close this issue 😂.

**Comment by saifulapm** [comment]
I am using Kitty terminal. I think some font not loading perfectly on others terminal. You can check my kitty config. https://github.com/saifulapm/dotfiles

**Comment by MatthewCushing** [comment]
I should've thought of that.  I saw you mention using kitty for best performance.  I'll look into Kitty's included font glyphs.  Thanks for pointing me in the right direction.
